Update connection.py
nickw444/nessclient pull request #43
Opened 2022-07-14 11:17 UTC by OzGav

Remove argument for asyncio.open_connection which is not supported in python3.10

2022-07-14 13:24 UTC, nickw444 requested changes

2022-07-14 13:24 UTC, nickw444 commented on nessclient/connection.py
> -            loop=self._loop,
Ideally we'd respect the user-provided `loop` that is passed to the constructor (when passed). 

I see that `open_connection` calls `loop.create_connection` (https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection), but they have a different return interface. Is there a trivial way to ensure the `loop` passed to the constructor is respected?

If not, then I think then I'd prefer for us to remove the ability to pass `loop` as a constructor argument if we don't respect it anyway. What do you think?

2022-07-14 13:26 UTC, nickw444 commented on nessclient/connection.py
> -            loop=self._loop,
From the sounds of thing having a user-provided `loop` might now be unnecessary anyway, so removal of the constructor arg sounds like the trivial way forward:

https://stackoverflow.com/a/60315290

2022-07-14 21:39 UTC, OzGav commented on nessclient/connection.py
> -            loop=self._loop,
So remove the argument at line 38 and then remove line 44?

2022-07-15 21:04 UTC, nickw444 commented on nessclient/connection.py
> -            loop=self._loop,
I think so - but doing that will no longer make this a drop-in library replacement and will require an upstream change and release in `core` in order to test this, since it unconditionally passes the `loop` argument. Wonder whether we should give some grace period by keeping this for now until a new version of HA goes out to bump the pinned dependency and remove the `loop` argument.

https://github.com/home-assistant/core/blob/2106c9f24723c422fd2d95b5d17e78c707e74e27/homeassistant/components/ness_alarm/__init__.py#L102

2022-07-15 21:51 UTC, OzGav commented on nessclient/connection.py
> -            loop=self._loop,
Entirely up to you. Just let me know if you would like anything else changed or tested. Mine is working fine with this single line removed.

2022-07-16 07:46 UTC, merged